[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "arena"
version = "0.0.1.dev0+dirty"
description = "A place to putz with Python."
authors = [{ name = "User Name", email = "user.name@nowhere.localhost" }]
dependencies = []
requires-python = ">= 3.10"                                                # EOL 31 Oct 2026

[dependency-groups]
dev = [
  "black",
  "flake8",
  "flake8-bugbear",
  "flake8-pyproject",
  "isort",
  "mypy",
  "pytest",
  "pytest-asyncio",
]

[project.scripts]
arena = "arena.__main__:main"

[tool.black]
line-length = 120

[tool.flake8]
exclude = ".venv"
extend-ignore = "E203,E501,E701"
extend-select = "B950"
max-line-length = 120
per-file-ignores = "__init__.py:F401"

[tool.mypy]
strict = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
filterwarnings = [
    "error",
    "default::DeprecationWarning",  # show but do not fail for deprecated bits used by deps
]
testpaths = ["tests"]

[tool.setuptools.packages.find]
where = ["src"]
